import type { Metadata } from "next";
import "./globals.css";
// import Nav from "@/components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const bodyStyle={
    background: 'var(--background)',
    color: 'var(--primary-text-color)'
  }
  
  return (
    <html lang="en">
      <body data-theme="dark" style={bodyStyle}>
        {children}
      </body>
    </html>
  );
}
